expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('expense_tracker_app.urls')),
]

expense_tracker_app/urls.py
"""Defines URL patterns for Expense Tracker App"""
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'expense_tracker_app'
urlpatterns = [
    # Home page:
    path('', views.index, name='index'),
    # Expense categories page (function):
    path('categories_function/', views.categories, name='categories_function'),
    # Expense categories page (class):
    path('categories/', login_required(views.CategoryView.as_view()), name='categories'),
    # Individual expenses page per category:
    path('category/<int:category_id>/', views.category, name='category'),
    # Page for adding new categories of expenses:
    path('add_category/', views.add_category, name='add_category'),
    # Page for deleting an existing category:
    path('delete_category/<int:category_id>', login_required(views.DeleteCategory.as_view()), name='delete_category'),
    # Page for adding new expenses:
    path('add_expense/', login_required(views.AddExpense.as_view()), name='add_expense'),
    # Page for editing existing expenses:
    path('edit_expense/<int:expense_id>/', login_required(views.EditExpense.as_view()), name='edit_expense'),
    # Page for deleting existing expenses:
    path('delete_expense/<int:expense_id>/', login_required(views.DeleteExpense.as_view()), name='delete_expense'),
    # Page displaying overview of all expenses per categories:
    path('overview/', login_required(views.OverviewView.as_view()), name='overview'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Page for registering new users:
    path('register/', views.register, name='register'),
    # Page for logging in exising users:
    path('login/', views.login, name='login'),
    # Page for users who logged themselves out:
    path('logout/', views.logout, name='logout'),
]

expense_tracker_app/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class Category(models.Model):
    """A category of expenses."""
    text = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        """Return a string presentation of the model"""
        return self.text


class Expense(models.Model):
    """Individual expenses inserted in the tracker."""
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    date_added = models.DateField(default=now())
    description = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'expenses'
        ordering = ('date_added',)  # sprawdzić, cze to zadziała tutaj

    def __str__(self):
        return f"{self.date_added} - {self.category} - {self.description} - {self.amount}"

    def save(self, *args, **kwargs):
        #        if not self.slug:
        #            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

expense_tracker_app/forms.py
from django import forms
from django.utils import timezone
from .models import Category, Expense


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['text']
        labels = {'text': ''}  # Here we can add some text above the inserted category title:
        widgets = {'text': forms.TextInput(attrs={'class': 'form-control'})}


class ExpenseForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        initial=Category.pk,
    )
    amount = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
    )
    date_added = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', }))
    description = forms.CharField(max_length=100, )


class DateForm(forms.Form):
    start = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    end = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the start field to the date of the earliest expense in the database
        earliest_expense = Expense.objects.order_by('date_added').first()
        if earliest_expense:
            self.fields['start'].initial = earliest_expense.date_added
        # Set the end field to today's date
        now = timezone.now()
        self.fields['end'].initial = now

expense_tracker_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.widgets import AdminDateWidget
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.db.models import Sum
from django.core.paginator import Paginator
import calendar
import plotly.express as px
from .models import Category, Expense
from .forms import CategoryForm, DateForm, ExpenseForm


def index(request):
    """The home page for Expense Tracker"""
    return render(request, 'expense_tracker_app/index.html')


@login_required()
def categories(request):
    """Page where user can see his expenses. Displayed as function."""
    categories = Category.objects.filter(owner=request.user)  # all() Tu trzeba jeszcze przefiltrowac po Userze
    context = {'categories': categories}
    return render(request, 'expense_tracker_app/categories.html', context)


class CategoryView(ListView):
    """Page where user can see his categories. Displayed as class.
    The @login_required decorator for the class view is applied in the views.py file."""
    model = Category
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.filter(owner=self.request.user)


@login_required()
def category(request, category_id):
    """Page displaying users expenses in a particular category."""
    category = Category.objects.get(id=category_id)
    if category.owner != request.user:
        raise Http404
    expenses = Expense.objects.filter(category=category)
    if request.GET.get('start_of_month'):
        # Set the start and end dates to the beginning and end of the current month
        now = timezone.now()
        start_date = now.replace(day=1)
        end_date = now.replace(day=calendar.monthrange(now.year, now.month)[1])
    else:
        start_date = request.GET.get('start')
        end_date = request.GET.get('end')
    # Filter the expenses based on the start and end dates
    if start_date:
        expenses = expenses.filter(date_added__gte=start_date)
    if end_date:
        expenses = expenses.filter(date_added__lte=end_date)
    total_expenses = expenses.aggregate(Sum('amount'))
    total_expenses_amount = total_expenses['amount__sum']
    if total_expenses_amount:
        formatted_total_expenses_amount = f"{total_expenses_amount:.2f}"
    # paginator = Paginator(expenses, 5)  # Show 5 expenses per page
    # page = request.GET.get('page')
    # expenses = paginator.get_page(page)
    if expenses:
        fig = px.bar(
            x=[expense.date_added for expense in expenses],
            y=[expense.amount for expense in expenses],
            labels={
                'x': "Date",
                'y': 'Amount PLN',
            },
            text=[expense.description for expense in expenses],
        )
        # fig.update_layout(title_text='Expenses in this categoory:')
        chart = fig.to_html()
        context = {'expenses': expenses, 'chart': chart, 'category': category, 'form': DateForm(),
                   'total_expenses_amount': formatted_total_expenses_amount}
    else:
        context = {'expenses': expenses, 'category': category}
    return render(request, 'expense_tracker_app/category.html', context)


@login_required()
def add_category(request):
    """Add a new category of expenses."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CategoryForm()
    else:
        # POST the form, add the category.
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.owner = request.user
            new_category.save()
            return redirect('expense_tracker_app:categories')
    context = {'form': form}
    return render(request, 'expense_tracker_app/add_category.html', context)


class DeleteCategory(DeleteView):
    """Delete an existing category."""
    model = Category
    pk_url_kwarg = 'category_id'

    def get_success_url(self):
        return reverse_lazy('expense_tracker_app:categories')


class AddExpense(CreateView):
    """Add a new expense. Select a category from the list of previously added categories, connected to your user."""
    model = Expense
    fields = ('category', 'amount', 'date_added', 'description')
    context_object_name = 'category_id'

    def get_form(self, form_class=None):
        form = super(AddExpense, self).get_form(form_class)
        form.fields['date_added'].widget = AdminDateWidget(attrs={'type': 'date', })
        for field in form.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        return form

    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields['category'].limit_choices_to = {'owner_id': self.request.user}
        return modelform

    def get(self, request):
        categories = Category.objects.filter(owner=self.request.user)
        context = {'categories': categories}
        if categories:
            additional_context = {'form': self.get_form()}
            context.update(additional_context)
        return render(request, 'expense_tracker_app/add_expense.html', context)

    def get_success_url(self):
        expense = self.object
        category_id = expense.category.pk
        return reverse('expense_tracker_app:category', kwargs={'category_id': category_id})


class EditExpense(UpdateView):
    """Edit a previously added expense."""
    model = Expense
    pk_url_kwarg = 'expense_id'
    fields = ('category', 'amount', 'date_added', 'description')

    def get_success_url(self):
        expense = self.get_object()
        category_id = expense.category.pk
        return reverse_lazy('expense_tracker_app:category', kwargs={'category_id': category_id})


class DeleteExpense(DeleteView):
    """Delete a previously added expense."""
    model = Expense
    pk_url_kwarg = 'expense_id'

    def get_success_url(self):
        expense = self.get_object()
        category_id = expense.category.pk
        return reverse_lazy('expense_tracker_app:category', kwargs={'category_id': category_id})


class OverviewView(ListView):
    """This view presents information of the user's whole expenses in the database divided by categories.
    It allows to see the on a pie chart the proportion between spending per each category"""
    model = Category
    context_object_name = 'categories'
    ordering = ('text',)

    def get(self, request):
        categories = Category.objects.filter(owner=self.request.user)
        expenses = Expense.objects.filter(category__in=categories, amount__gte=1)
        expenses_total_amount = expenses.values('category').annotate(sum=Sum('amount'))
        category_labels = [category.text for category in categories]
        expense_values = [expense['sum'] for expense in expenses_total_amount]
        fig = px.pie(
            # labels=category_labels,
            values=expense_values,
        )
        fig.update_traces(
            title_text='Expenses by category in percent',
            title_position='bottom center',
            textposition='inside',
            textinfo='text+percent',
            text=[label for label in category_labels],
            hovertext='percent',
            # showlegend=True,
            automargin=True,
            insidetextorientation='radial',
        )

        chart = fig.to_html()
        context = {
            'categories': categories,
            'chart': chart,
            'expenses': expenses,
        }
        return render(request, 'expense_tracker_app/overview.html', context)

expense_tracker_app/templates/expense_tracker_app/add_category.html
{% extends "expense_tracker_app/base.html" %}

{% block title %}
ET - Add category
{% endblock title %}
{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> Add category </span>
{% endblock page_header %}

{% block content %}
<div class="container mt-auto pt-5">
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-header">
                <strong>Add a new category:</strong>
              </div>
            <div class="card-body">
                <form action="{% url 'expense_tracker_app:add_category' %}"
                      method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                  <div class="d-flex justify-content-center">
                    <button class="btn btn-info" name="submit">Add</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
        {% endblock content %}

expense_tracker_app/templates/expense_tracker_app/add_expense.html
{% extends "expense_tracker_app/base.html" %}
{% load widget_tweaks %}

{% block title %}
ET - Add expense
{% endblock title %}

{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> Add expense </span>
{% endblock page_header %}

{% block content %}
<div class="container mt-auto pt-5">
    {% if not categories %}
    <div class="text-center">
        <h3>Looks like there are no categories yet.</h3>
        <p>Start by adding a category.</p>
        <p><a href="{% url 'expense_tracker_app:add_category' %}" class="btn btn-info">Add a new category</a>
        </p>
    </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-header">
                <strong>Add a new expense:</strong>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <button class="btn btn-info" name="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}

</div>
{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" git-->
    <!--          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="col-8 d-flex">
            <a class="navbar-brand" href="{% url 'expense_tracker_app:index' %}">Expense Tracker App</a>
            <ul class="navbar-nav">
                {% with url_name=request.resolver_match.url_name %}
                {% if user.is_authenticated %}
                <li class="nav-item {% if url_name == 'overview' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'expense_tracker_app:overview' %}">Overview</a>
                </li>
                <li class="nav-item {% if url_name == 'categories' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'expense_tracker_app:categories' %}">List of categories</a>
                </li>
                <li class="nav-item {% if url_name == 'add_category' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'expense_tracker_app:add_category' %}">Add category</a>
                </li>
                <li class="nav-item {% if url_name == 'add_expense' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'expense_tracker_app:add_expense' %}">Add expense</a>
                </li>

                {% endif %}
                {% endwith %}
            </ul>
        </div>
        <div class="col4 d-flex justify-content-end">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <div class="nav-link"> Hello, {{ user.username }}.</div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<main>
    <div class="container">
        <div class="col-12 d-flex pt-2 pb-2">{% block page_header %}{%endblock page_header %}</div>
        <div>{% block content %}{% endblock content%}</div>
    </div>
</main>
<footer class="footer mt-auto py-1 sticky-bottom">
    <hr/>
    <div class="container">
        <p class="text-secondary"><small> Copyright 2023 &#174; Wojciech Maniak</small></p>
    </div>
</footer>

</body>
</html>

expense_tracker_app/templates/expense_tracker_app/category.html
{% extends "expense_tracker_app/base.html" %}

{% block title %}
ET - {{ category.text }} - expenses
{% endblock title %}

{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> <a
        href="{% url 'expense_tracker_app:categories' %}" class="text-decoration-none">Categories</a>
    -> {{ category }}</span>
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="page-title">
        <span>{{ category }}</span>
    </div>
    {% if expenses %}
    <div class="row my-3">
        <div class="col-8">
            <form method="get">
                {% for field in form %}
                {{ field.label_tag }} {{ field }}
                {% endfor %}
                <!--                <button class="btn btn-info"><input type="submit" value="Filter"></button>-->
                <input class="btn btn-info" type="submit" value="Filter">
                <input class="btn btn-info" type="submit" name="start_of_month" value="From start of month">
                <button class="btn btn-info"><a class="text-white"
                                                href="{% url 'expense_tracker_app:category' category.id  %}">Reset</a>
                </button>
            </form>
        </div>
        <div class="col-4 d-flex justify-content-end">
            <a href="{% url 'expense_tracker_app:add_expense' %}" class="btn btn-info mx-1">Add an expense</a>
            <a href="{% url 'expense_tracker_app:delete_category' category.id%}" class="btn btn-danger mx-1">Delete
                category</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-bordered">
            <tr class="bg-info text-white">
                <th>Date:</th>
                <th>Description:</th>
                <th>Amount:</th>
                <th>Edit / delete:</th>
            </tr>
            {% for expense in expenses %}
            <tr>
                <td>{{ expense.date_added|date:'Y-M-d' }}</td>
                <td>{{ expense.description }}</td>
                <td>{{ expense.amount }}</td>
                <td align="center"><a href="{% url 'expense_tracker_app:edit_expense' expense.id %}"> edit </a> -
                    <a href="{% url 'expense_tracker_app:delete_expense' expense.id %}"> delete </a></td>
            </tr>

            {% empty %}
            <h2>There are no expenses in this category for selected dates. Try selecting other dates.</h2>
            {% endfor %}
            <tr bgcolor="lightgrey">
                <th width="150">Number of entries: {{ expenses.count }}</th>
                <th width="300">Total amount:</th>
                <th width="150"> {{ total_expenses_amount }}</th>
                <th width="150"></th>
            </tr>
        </table>
    </div>
    <div class="row">
        {{ chart|safe }}"
    </div>
    {% else %}
    <div class="row my-2">
        <div class="col d-flex justify-content-center">
            <h6>There are no expenses in this category with selected criteria.</h6>
        </div>
    </div>
    <div class="row my-2">
        <div class="col d-flex justify-content-center">
            <a href="{% url 'expense_tracker_app:category' category.id %}" class="btn btn-info mx-1">Reset the date
                filter</a>
            <a href="{% url 'expense_tracker_app:categories' %}" class="btn btn-info mx-1">Return to the list of
                categories</a>
            <a href="{% url 'expense_tracker_app:add_expense' %}" class="btn btn-info mx-1">Add an expense</a>
            <a href="{% url 'expense_tracker_app:delete_category' category.id%}" class="btn btn-danger mx-1">Delete
                category</a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/category_confirm_delete.html
{% extends "expense_tracker_app/base.html" %}

{% block title %}
ET - Delete category
{% endblock title %}

{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> Delete category</span>
{% endblock page_header %}

{% block content %}
<div class="row">
    <div class="col d-flex justify-content-center">
        <h4>Delete category</h4>
    </div>
</div>
<div class="row">
    <div class="col d-flex justify-content-center">
        <div class="card">
            <form method="post">
                <strong>Are you sure you want to delete "{{ object }}"?</strong>
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-danger" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/category_list.html
{% extends "expense_tracker_app/base.html" %}

{% block title %}
ET - Categories
{% endblock title %}

{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> Categories</span>
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="row my-4">
        <div class="col-12">
            {% if categories %}
            <div class="page-title">
                <span>Your expense categories</span>
            </div>
            <div class="row">
                <div class="d-flex flex-wrap w-100">
                    {% for category in categories %}
                    <div class="col-3 mb-3">
                        <a href="{% url 'expense_tracker_app:category' category.id %}"
                           class="card text-info">
                            <div class="card-body text-center">
                                <h6>{{ category }}</h6>
                            </div>
                        </a>
                    </div>

                    {% endfor %}
                </div>
            </div>

            {% else %}
            <div class="text-center">
                <h3>Looks like there are no categories yet.</h3>
                <p>Start by adding a category.</p>
                <p><a href="{% url 'expense_tracker_app:add_category' %}"
                      class="btn btn-info btn">Add a new category</a></p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/expense_confirm_delete.html
{% extends "expense_tracker_app/base.html" %}

{% block title %}
ET - Delete expense
{% endblock title %}
{% block page_header %}
<p>Expense tracker - delete expense header</p>
{% endblock page_header %}

{% block content %}

<p>Delete expense:</p>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/expense_form.html
{% extends "expense_tracker_app/base.html" %}
{% load widget_tweaks %}

{% block title %}
ET - Add expense
{% endblock title %}

{% block page_header %}
<p>Expense tracker - Add expense header</p>
{% endblock page_header %}

{% block content %}
<div class="container mt-auto pt-5">
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-header">
                <strong>Add an expense:</strong>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-info" name="submit">Add expense</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/index.html
{% extends "expense_tracker_app/base.html" %}
{% load static %}
{% block title %}
ET - home page
{% endblock title %}

{% block page_header %}
<!--<span>Home page</span>-->
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col mt-5">
            <div class="page-title">
                <span>Expense Tracker App - Home Page</span>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-7 pt-5">
            {% if user.is_authenticated %}
            <p>Hi {{ user.username }}, nice to see you are in control!</p>
            <p>
                <a href="{% url 'expense_tracker_app:add_category' %}" class="btn btn-info">Add a
                    category</a>
                <a href="{% url 'expense_tracker_app:add_expense' %}" class="btn btn-info">Add an expense</a>
            </p>
            {% else %}
            <p>How many times have you asked yourself "where's my money?!" How many times have you experienced that
                uncomfortable situation, when you're at the cash counter, trying to make a payment and failing to do
                so?</p>
            <p>Well if it was even once, than you're correct thinking it was one time too many. But don't worry, it
                won't happen again. </p>
            <p>The Expense Tracker Application is a simple but efficient online platform, which is going to help you
                keep track of your spending. And more awareness of where does your money go will surely mean less
                surprises that it is not where you expected it to be - your account.</p>
            <p>So go ahead, create an account and start being in control from right now onwards!</p>
            <p>
                <a href="{% url 'users:login' %}" class="btn btn-info">Log in</a>
                <a href="{% url 'users:register' %}" class="btn btn-info">Create an account</a>
            </p>
            {% endif %}
        </div>
        <div class="col-5 pt-5">
            {% if user.is_authenticated %}
            <img src="{% static 'pics/guy-in-control.png' %}" class="img-fluid">
            {% else %}
            <img src="{% static 'pics/empty-pocket-guy.png' %}" class="img-fluid">
            {% endif %}
        </div>
    </div>
    <div class="row">

    </div>
</div>
{% endblock content %}

expense_tracker_app/templates/expense_tracker_app/overview.html
{% extends "expense_tracker_app/base.html" %}
{% load expense_filters %}

{% block title %}
ET - Overview
{% endblock title %}

{% block page_header %}
<span> <a href="{% url 'expense_tracker_app:index' %}" class="text-decoration-none">Home</a> -> Overview</span>
{% endblock page_header %}

{% block content %}
<div class="container">
    {% if categories %}
    {% if expenses %}
    <div class="page-title">
        <span>Your expenses overview</span>
    </div>
    <div class="row">
        <div class="col-6">
            <table class="table table-bordered">
                <tr class="bg-info text-white">
                    <th width="60%">Category:</th>
                    <th>Total amount:</th>
                </tr>
                {% for category in categories %}
                {% if category|sum_expenses is not None %}
                <tr>
                    <td>{{ category.text }}</td>
                    <td>{{ category|sum_expenses }}</td>
                </tr>
                {% endif %}
                {% endfor %}

            </table>
            <div class="mt-4">
                <a href="{% url 'expense_tracker_app:add_category' %}"
                   class="btn btn-info mx-2">Add a new category</a>
                <a href="{% url 'expense_tracker_app:add_expense' %}" class="btn btn-info">Add a new
                    expense</a>
            </div>
        </div>
        <div class="col-6">
            {{ chart|safe }}
        </div>
    </div>
    {% else %}
    <div class="row my-4">
        <div class="col-12">
            <div class="text-center">
                <h3>Looks like there are no expenses yet.</h3>
                <p>Start by adding an expense.</p>
                <p><a href="{% url 'expense_tracker_app:add_expense' %}" class="btn btn-info">Add a new expense</a>
                </p>
            </div>
        </div>
    </div>
    {% endif %}
    {% else %}
    <div class="row my-4">
        <div class="col-12">
            <div class="text-center">
                <h3>Looks like there are no categories yet.</h3>
                <p>Start by adding a category.</p>
                <p><a href="{% url 'expense_tracker_app:add_category' %}" class="btn btn-info">Add a new category</a>
                </p>
            </div>
        </div>
    </div>
    {% endif %}


</div>
{% endblock content %}